name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Q03_57 Test 1
      id: q03_57-test-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Q03_57 Test 1
        setup-command: javac Q03_57/Coins.java
        command: java -cp Q03_57 Coins
        input: |-
          5
          0
          0
        expected-output: The amount is $1.25
        comparison-method: contains
        timeout: 10
        max-score: 2
    - name: Q03_57 Test 2
      id: q03_57-test-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Q03_57 Test 2
        setup-command: javac Q03_57/Coins.java
        command: java -cp Q03_57 Coins
        input: |-
          0
          15
          0
        expected-output: The amount is $1.50
        comparison-method: contains
        timeout: 10
        max-score: 2
    - name: Q03_57 Test 3
      id: q03_57-test-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Q03_57 Test 3
        setup-command: javac Q03_57/Coins.java
        command: java -cp Q03_57 Coins
        input: |-
          0
          0
          40
        expected-output: The amount is $2.00
        comparison-method: contains
        timeout: 10
        max-score: 2
    - name: Q03_57 Test 4
      id: q03_57-test-4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Q03_57 Test 4
        setup-command: javac Q03_57/Coins.java
        command: java -cp Q03_57 Coins
        input: |-
          10
          25
          10
        expected-output: The amount is $5.50
        comparison-method: contains
        timeout: 10
        max-score: 2
    - name: Q03_63 Test 1
      id: q03_63-test-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Q03_63 Test 1
        setup-command: javac Q03_63/FutureValues.java
        command: java -cp Q03_63 FutureValues
        input: |-
          500
          0
        expected-output: |-
          With an investment of $500.00
          at an interest rate of 0.00% compounded annually:
          the future value in 5 years is $500.00
          the future value in 10 years is $500.00
          the future value in 20 years is $500.00
        comparison-method: contains
        timeout: 10
        max-score: 2
    - name: Q03_63 Test 2
      id: q03_63-test-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Q03_63 Test 2
        setup-command: javac Q03_63/FutureValues.java
        command: java -cp Q03_63 FutureValues
        input: |-
          500
          .045
        expected-output: |-
          With an investment of $500.00
          at an interest rate of 4.50% compounded annually:
          the future value in 5 years is $623.09
          the future value in 10 years is $776.48
          the future value in 20 years is $1,205.86
        comparison-method: contains
        timeout: 10
        max-score: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        Q03_57-TEST-1_RESULTS: "${{steps.q03_57-test-1.outputs.result}}"
        Q03_57-TEST-2_RESULTS: "${{steps.q03_57-test-2.outputs.result}}"
        Q03_57-TEST-3_RESULTS: "${{steps.q03_57-test-3.outputs.result}}"
        Q03_57-TEST-4_RESULTS: "${{steps.q03_57-test-4.outputs.result}}"
        Q03_63-TEST-1_RESULTS: "${{steps.q03_63-test-1.outputs.result}}"
        Q03_63-TEST-2_RESULTS: "${{steps.q03_63-test-2.outputs.result}}"
      with:
        runners: q03_57-test-1,q03_57-test-2,q03_57-test-3,q03_57-test-4,q03_63-test-1,q03_63-test-2
